
// src/lib/constants.ts
import type { GeneratedCode, SocioVipMember, PlatformUserRole } from "./types";

export const GENERATED_CODE_STATUS_TRANSLATIONS: Record<GeneratedCode['status'], string> = {
  available: "Disponible",
  redeemed: "Canjeado/Utilizado",
  expired: "Vencido",
};

export const GENERATED_CODE_STATUS_COLORS: Record<GeneratedCode['status'], "default" | "secondary" | "destructive" | "outline"> = {
    available: "default", 
    redeemed: "secondary",
    expired: "destructive",
};

export const MEMBERSHIP_STATUS_TRANSLATIONS: Record<SocioVipMember['membershipStatus'], string> = {
  active: "Activa",
  inactive: "Inactiva",
  pending_payment: "Pendiente Pago",
  cancelled: "Cancelada",
};

export const MEMBERSHIP_STATUS_COLORS: Record<SocioVipMember['membershipStatus'], "default" | "secondary" | "destructive" | "outline"> = {
    active: "default", 
    inactive: "secondary",
    pending_payment: "outline", 
    cancelled: "destructive",
};

export const MESES_DEL_ANO_ES = [
  "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
  "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
];

export const ALL_PLATFORM_USER_ROLES: PlatformUserRole[] = ['superadmin', 'business_admin', 'staff', 'promoter', 'host'];

export const PLATFORM_USER_ROLE_TRANSLATIONS: Record<PlatformUserRole | 'QrClient' | 'SocioVipMember', string> = {
  superadmin: "Super Admin",
  business_admin: "Admin Negocio",
  staff: "Staff Negocio",
  promoter: "Promotor",
  host: "Anfitrión",
  QrClient: "Cliente QR",
  SocioVipMember: "Socio VIP",
};

export const ROLES_REQUIRING_BUSINESS_ID: PlatformUserRole[] = ['business_admin', 'staff', 'host'];

export const BUSINESS_TYPES = [
  "Restaurante",
  "Bar",
  "Discoteca",
  "Hotel",
  "Tienda Retail",
  "Gimnasio",
  "Salón de Belleza",
  "Servicios Profesionales",
  "Entretenimiento",
  "Educación",
  "Salud y Bienestar",
  "Viajes y Turismo",
  "Otro",
] as const;


// Ubigeo Data
export const PERU_LOCATIONS = {
  "AMAZONAS": {
    "BAGUA": ["ARAMANGO", "BAGUA", "COPALLIN", "EL PARCO", "IMAZA", "LA PECA"],
    "BONGARA": ["CHISQUILLA", "CHURUJA", "COROSHA", "CUISPES", "FLORIDA", "JAZAN", "JUMBILLA", "RECTA", "SAN CARLOS", "SHIPASBAMBA", "VALERA", "YAMBRASBAMBA"],
    "CHACHAPOYAS": ["ASUNCION", "BALSAS", "CHACHAPOYAS", "CHETO", "CHILIQUIN", "CHUQUIBAMBA", "GRANADA", "HUANCAS", "LA JALCA", "LEIMEBAMBA", "LEVANTO", "MAGDALENA", "MARISCAL CASTILLA", "MOLINOPAMPA", "MONTEVIDEO", "OLLEROS", "QUINJALCA", "SAN FRANCISCO DE DAGUAS", "SAN ISIDRO DE MAINO", "SOLOCO", "SONCHE"],
    "CONDORCANQUI": ["EL CENEPA", "NIEVA", "RIO SANTIAGO"],
    "LUYA": ["CAMPORREDONDO", "COCABAMBA", "COLCAMAR", "CONILA", "INGUILPATA", "LAMUD", "LONGUITA", "LONYA CHICO", "LUYA", "LUYA VIEJO", "MARIA", "OCALLI", "OCUMAL", "PISUQUIA", "PROVIDENCIA", "SAN CRISTOBAL", "SAN FRANCISCO DEL YESO", "SAN JERONIMO", "SAN JUAN DE LOPECANCHA", "SANTA CATALINA", "SANTO TOMAS", "TRITA"],
    "RODRIGUEZ DE MENDOZA": ["CHIRIMOTO", "COCHAMAL", "HUAMBO", "LIMABAMBA", "LONGAR", "MARISCAL BENAVIDES", "MILPUC", "OMIA", "SAN NICOLAS", "SANTA ROSA", "TOTORA", "VISTA ALEGRE"],
    "UTCUBAMBA": ["BAGUA GRANDE", "CAJARURO", "CUMBA", "EL MILAGRO", "JAMALCA", "LONYA GRANDE", "YAMON"]
  },
  "ANCASH": {
    "AIJA": ["AIJA", "CORIS", "HUACLLAN", "LA MERCED", "SUCCHA"],
    "ANTONIO RAYMONDI": ["ACZO", "CHACCHO", "CHINGAS", "LLAMELLIN", "MIRGAS", "SAN JUAN DE RONTOY"],
    "ASUNCION": ["ACOCHACA", "CHACAS"],
    "BOLOGNESI": ["ABELARDO PARDO LEZAMETA", "ANTONIO RAYMONDI", "AQUIA", "CAJACAY", "CANIS", "CHIQUIAN", "COLQUIOC", "HUALLANCA", "HUASTA", "LA PRIMAVERA", "MANGAS", "PACLLON", "SAN MIGUEL DE CORPANQUI", "TICLLOS"],
    "CARHUAZ": ["ACOPAMPA", "AMASHCA", "ANTA", "ATAQUERO", "CARHUAZ", "MARCARA", "PARIAHUANCA", "SAN MIGUEL DE ACO", "SHILLA", "TINCO", "YUNGAR"],
    "CARLOS F. FITZCARRALD": ["SAN LUIS", "SAN NICOLAS", "YAUYA"],
    "CASMA": ["BUENA VISTA ALTA", "CASMA", "COMANDANTE NOEL", "YAUTAN"],
    "CORONGO": ["ACO", "BAMBAS", "CORONGO", "CUSCA", "LA PAMPA", "YANAC", "YUPAN"],
    "HUARI": ["ANRA", "CAJAY", "CHAVIN DE HUANTAR", "HUACACHI", "HUACCHIS", "HUACHIS", "HUANTAR", "HUARI", "MASIN", "PAUCAS", "PONTO", "RAHUAPAMPA", "RAPAYAN", "SAN MARCOS", "SAN PEDRO DE CHANA", "UCO"],
    "HUARMEY": ["COCHAPETI", "CULEBRAS", "HUARMEY", "HUAYAN", "MALVAS"],
    "HUARAZ": ["COCHABAMBA", "COLCABAMBA", "HUANCHAY", "HUARAZ", "INDEPENDENCIA", "JANGAS", "LA LIBERTAD", "OLLEROS", "PAMPAS", "PARIACOTO", "PIRA", "TARICA"],
    "HUAYLAS": ["CARAZ", "HUALLANCA", "HUATA", "HUAYLAS", "MATO", "PAMPAROMAS", "PUEBLO LIBRE", "SANTA CRUZ", "SANTO TORIBIO", "YURACMARCA"],
    "MARISCAL LUZURIAGA": ["CASCA", "ELEAZAR GUZMAN BARRON", "FIDEL OLIVAS ESCUDERO", "LLAMA", "LLUMPA", "LUCMA", "MUSGA", "PISCOBAMBA"],
    "OCROS": ["ACAS", "CAJAMARQUILLA", "CARHUAPAMPA", "COCHAS", "CONGAS", "LLIPA", "OCROS", "SAN CRISTOBAL DE RAJAN", "SAN PEDRO", "SANTIAGO DE CHILCAS"],
    "PALLASCA": ["BOLOGNESI", "CABANA", "CONCHUCOS", "HUACASCHUQUE", "HUANDOVAL", "LACABAMBA", "LLAPO", "PALLASCA", "PAMPAS", "SANTA ROSA", "TAUCA"],
    "POMABAMBA": ["HUAYLLAN", "PAROBAMBA", "POMABAMBA", "QUINUABAMBA"],
    "RECUAY": ["CATAC", "COTAPARACO", "HUAYLLAPAMPA", "LLACLLIN", "MARCA", "PARARIN", "RECUAY", "TAPACOCHA", "TICAPAMPA"],
    "SANTA": ["CACERES DEL PERU", "CHIMBOTE", "COISHCO", "MACATE", "MORO", "NEPEÑA", "NUEVO CHIMBOTE", "SAMANCO", "SANTA"],
    "SIHUAS": ["ACOBAMBA", "ALFONSO UGARTE", "CASHAPAMPA", "CHINGALPO", "HUAYLLABAMBA", "QUICHES", "RAGASH", "SAN JUAN", "SICSIBAMBA", "SIHUAS"],
    "YUNGAY": ["CASCAPARA", "MANCOS", "MATACOTO", "QUILLO", "RANRAHIRCA", "SHUPLUY", "YANAMA", "YUNGAY"]
  },
  "APURIMAC": {
    "ABANCAY": ["ABANCAY", "CHACOCHE", "CIRCA", "CURAHUASI", "HUANIPACA", "LAMBRAMA", "PICHIRHUA", "SAN PEDRO DE CACHORA", "TAMBURCO"],
    "ANDAHUAYLAS": ["ANDAHUAYLAS", "ANDARAPA", "CHIARA", "HUANCARAMA", "HUANCARAY", "HUAYANA", "JOSE MARIA ARGUEDAS", "KAQUIABAMBA", "KISHUARA", "PACOBAMBA", "PACUCHA", "PAMPACHIRI", "POMACOCHA", "SAN ANTONIO DE CACHI", "SAN JERONIMO", "SAN MIGUEL DE CHACCRAMPA", "SANTA MARIA DE CHICMO", "TALAVERA", "TUMAY HUARACA", "TURPO"],
    "ANTABAMBA": ["ANTABAMBA", "EL ORO", "HUAQUIRCA", "JUAN ESPINOZA MEDRANO", "OROPESA", "PACHACONAS", "SABAINO"],
    "AYMARAES": ["CAPAYA", "CARAYBAMBA", "CHALHUANCA", "CHAPIMARCA", "COLCABAMBA", "COTARUSE", "HUAYLLO", "JUSTO APU SAHUARAURA", "LUCRE", "POCOHUANCA", "SAN JUAN DE CHACÑA", "SAÑAYCA", "SORAYA", "TAPAIRIHUA", "TINTAY", "TORAYA", "YANACA"],
    "CHINCHEROS": ["ANCO-HUALLO", "CHINCHEROS", "COCHARCAS", "HUACCANA", "OCOBAMBA", "ONGOY", "RANRACANCHA", "URANMARCA"],
    "COTABAMBAS": ["CHALLHUAHUACHO", "COTABAMBAS", "COYLLURQUI", "HAQUIRA", "MARA", "TAMBOBAMBA"],
    "GRAU": ["CHUQUIBAMBILLA", "CURASCO", "CURPAHUASI", "GAMARRA", "HUAYLLATI", "MAMARA", "MICAELA BASTIDAS", "PATAYPAMPA", "PROGRESO", "SAN ANTONIO", "SANTA ROSA", "TURPAY", "VILCABAMBA", "VIRUNDO"]
  },
  // ... (más departamentos)
  "LIMA": {
    "LIMA": ["ANCON", "ATE", "BARRANCO", "BREÑA", "CARABAYLLO", "CHACLACAYO", "CHORRILLOS", "CIENEGUILLA", "COMAS", "EL AGUSTINO", "INDEPENDENCIA", "JESUS MARIA", "LA MOLINA", "LA VICTORIA", "LIMA", "LINCE", "LOS OLIVOS", "LURIGANCHO", "LURIN", "MAGDALENA DEL MAR", "MAGDALENA VIEJA", "MIRAFLORES", "PACHACAMAC", "PUCUSANA", "PUEBLO LIBRE", "PUENTE PIEDRA", "PUNTA HERMOSA", "PUNTA NEGRA", "RIMAC", "SAN BARTOLO", "SAN BORJA", "SAN ISIDRO", "SAN JUAN DE LURIGANCHO", "SAN JUAN DE MIRAFLORES", "SAN LUIS", "SAN MARTIN DE PORRES", "SAN MIGUEL", "SANTA ANITA", "SANTA MARIA DEL MAR", "SANTA ROSA", "SANTIAGO DE SURCO", "SURQUILLO", "VILLA EL SALVADOR", "VILLA MARIA DEL TRIUNFO"],
    "BARRANCA": ["BARRANCA", "PARAMONGA", "PATIVILCA", "SUPE", "SUPE PUERTO"],
    "CAJATAMBO": ["CAJATAMBO", "COPA", "GORGOR", "HUANCAPON", "MANAS"],
    "CANTA": ["ARAHUAY", "CANTA", "HUAMANTANGA", "HUAROS", "LACHAQUI", "SAN BUENAVENTURA", "SANTA ROSA DE QUIVES"],
    "CAÑETE": ["ASIA", "CALANGO", "CERRO AZUL", "CHILCA", "COAYLLO", "IMPERIAL", "LUNAHUANA", "MALA", "NUEVO IMPERIAL", "PACARAN", "QUILMANA", "SAN ANTONIO", "SAN LUIS", "SAN VICENTE DE CAÑETE", "SANTA CRUZ DE FLORES", "ZUÑIGA"],
    "HUARAL": ["ATAVILLOS ALTO", "ATAVILLOS BAJO", "AUCALLAMA", "CHANCAY", "HUARAL", "IHUARI", "LAMPIAN", "PACARAOS", "SAN MIGUEL DE ACOS", "SANTA CRUZ DE ANDAMARCA", "SUMBILCA", "VEINTISIETE DE NOVIEMBRE"],
    "HUAROCHIRI": ["ANTIOQUIA", "CALLAHUANCA", "CARAMPOMA", "CHICLA", "CUENCA", "HUACHUPAMPA", "HUANZA", "HUAROCHIRI", "LAHUAYTAMBO", "LANGA", "LARAOS", "MARIATANA", "MATUCANA", "RICARDO PALMA", "SAN ANDRES DE TUPICOCHA", "SAN ANTONIO", "SAN BARTOLOME", "SAN DAMIAN", "SAN JUAN DE IRIS", "SAN JUAN DE TANTARANCHE", "SAN LORENZO DE QUINTI", "SAN MATEO", "SAN MATEO DE OTAO", "SAN PEDRO DE CASTA", "SAN PEDRO DE HUANCAYRE", "SANGALLAYA", "SANTA CRUZ DE COCACHACRA", "SANTA EULALIA", "SANTIAGO DE ANCHUCAYA", "SANTIAGO DE TUNA", "SANTO DOMINGO DE LOS OLLEROS", "SURCO"],
    "HUAURA": ["AMBAR", "CALETA DE CARQUIN", "CHECRAS", "HUACHO", "HUALMAY", "HUAURA", "LEONCIO PRADO", "PACCHO", "SANTA LEONOR", "SANTA MARIA", "SAYAN", "VEGUETA"],
    "OYON": ["ANDAJES", "CAUJUL", "COCHAMARCA", "NAVAN", "OYON", "PACHANGARA"],
    "YAUYOS": ["ALIS", "AYAUCA", "AYAVIRI", "AZANGARO", "CACRA", "CARANIA", "CATAHUASI", "CHOCOS", "COCHAS", "COLONIA", "HONGOS", "HUAMPARA", "HUANCAYA", "HUANGASCAR", "HUANTAN", "HUAÑEC", "LARAOS", "LINCHA", "MADEAN", "MIRAFLORES", "OMAS", "PUTINZA", "QUINCHES", "QUINOCAY", "SAN JOAQUIN", "SAN PEDRO DE PILAS", "TANTA", "TAURIPAMPA", "TOMAS", "TUPE", "VIÑAC", "VITIS", "YAUYOS"]
  }
  // ... (el resto de departamentos, provincias y distritos de Perú)
};


